name: "Check"

on: [push]

jobs:
  javascript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: ESLint
        run: npm run lint -- --format json --output-file ./report.json

      - name: Report Failures
        if: always()
        uses: beaucollins/psalm-annotations-action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          report_name: eslint
          report_title: ESLint
          report_path: ./report.json
          report_type: eslint
